// <auto-generated />
namespace PronosContest.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10017));
        
        string IMigrationMetadata.Id
        {
            get { return "201606081048303_1.0.0.17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
