// <auto-generated />
namespace PronosContest.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1007 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1007));
        
        string IMigrationMetadata.Id
        {
            get { return "201605140921448_1.0.0.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
